# Generated by Django 6.1 on 2026-08-13 10:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exercise',
            name='exercise_type',
            field=models.CharField(choices=[('MULTIPLE_CHOICE', 'Multiple Choice'), ('TRANSLATE', 'Translate'), ('MATCH_PAIRS', 'Match Pairs'), ('FILL_BLANK', 'Fill in the Blank'), ('TYPE_ANSWER', 'Type Answer')], default='MULTIPLE_CHOICE', max_length=50),
        ),
    ]
