# Generated by Django 5.2.17 on 2026-08-13 15:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_userexercisesubmission_dailyprogress'),
    ]

    operations = [
        migrations.AddField(
            model_name='exercise',
            name='audio_text',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='exercise',
            name='exercise_type',
            field=models.CharField(choices=[('MULTIPLE_CHOICE', 'Multiple Choice'), ('TRANSLATE', 'Translate'), ('MATCH_PAIRS', 'Match Pairs'), ('FILL_BLANK', 'Fill in the Blank'), ('TYPE_ANSWER', 'Type Answer'), ('LISTENING', 'Listening'), ('SPEAKING', 'Speaking')], default='MULTIPLE_CHOICE', max_length=50),
        ),
    ]
